spring.application.name=cse
server.port=4000

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/tt
spring.datasource.username=root
spring.datasource.password=ptr3



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true